
spring.profiles.active=daily
server.port=7006


spring.datasource.url=${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/charging?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driverClassName= com.mysql.cj.jdbc.Driver


spring.smart-retry.mybatis.enabled=true
spring.smart-retry.mybatis.datasource=dataSource
